# Generated by Django 3.2.5 on 2021-07-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210709_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countrymodel',
            table='country',
        ),
    ]
